
import java.io.File;
import java.io.FileWriter;
import java.util.Iterator;
import java.util.LinkedList;
import java.util.Queue;
import java.util.Scanner;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author User
 */
public class Sellers extends javax.swing.JFrame {


     Queue<Seller> allsellers = new LinkedList<>();
    
    public Sellers() {
        initComponents();
        readAllData();
        displayAllData(); 
    }
    
    void displayAllData() {
        sellertxt.setText("");
        for(Seller seller : allsellers) {
            sellertxt.append(seller.getId() + "   " + seller.getAge() + "      " + seller.getSupname() + "      " + seller.getGender() + "      " + seller.getAddress() + "      " + seller.getContactnum());
        }
    }
    
      void readAllData() {
        try {
            File supFile = new File("sellerdata.txt"); 
            Scanner scanner = new Scanner(supFile);
         
            while(scanner.hasNextLine()) {
                String data = scanner.nextLine();
                String[] currentdata = data.split(";");
                Seller seller = new Seller();
                seller.setId(Integer.parseInt(currentdata[0]));
                seller.setAge(Integer.parseInt(currentdata[1]));
                seller.setSupname(currentdata[2]);
                seller.setGender(currentdata[3]);
                seller.setAddress(currentdata[4]);
                seller.setContactnum(currentdata[5]);
                allsellers.offer(seller); // add to queue
            }
         
            scanner.close();
        } catch(Exception e) {
            e.printStackTrace();
        }
    }
      
      

    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        sellerid = new javax.swing.JTextField();
        sellername = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        sellerage = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        sellergender = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        selleraddress = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        sellercontact = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btnsave = new javax.swing.JButton();
        btnsearch = new javax.swing.JButton();
        btndel = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        sellertxt = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 255, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-seller-100.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 100, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Sellers");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 26, 77, -1));

        jPanel3.setBackground(new java.awt.Color(153, 255, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Seller Info");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(356, 19, 107, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Id");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 93, 54, -1));
        jPanel3.add(sellerid, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 88, 228, -1));
        jPanel3.add(sellername, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 116, 228, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Name");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 121, 54, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Age");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 149, 54, -1));
        jPanel3.add(sellerage, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 144, 228, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Gender");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 177, 54, -1));
        jPanel3.add(sellergender, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 172, 228, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Address");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 205, 54, -1));
        jPanel3.add(selleraddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 200, 228, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Contact");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 233, 54, -1));
        jPanel3.add(sellercontact, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 228, 228, -1));

        jButton1.setBackground(new java.awt.Color(102, 255, 153));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, 66, -1));

        btnsave.setBackground(new java.awt.Color(102, 255, 153));
        btnsave.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnsave.setText("Save");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });
        jPanel3.add(btnsave, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 66, -1));

        btnsearch.setBackground(new java.awt.Color(102, 255, 153));
        btnsearch.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnsearch.setText("Search");
        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });
        jPanel3.add(btnsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, -1, -1));

        btndel.setBackground(new java.awt.Color(102, 255, 153));
        btndel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btndel.setText("Delete");
        btndel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndelActionPerformed(evt);
            }
        });
        jPanel3.add(btndel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, 66, -1));

        sellertxt.setColumns(20);
        sellertxt.setRows(5);
        jScrollPane1.setViewportView(sellertxt);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(409, 88, 380, 210));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 812, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btndelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndelActionPerformed
         if (sellerid.getText()!= null) {
        try {
            int id = Integer.parseInt(sellerid.getText());
            deleteSeller(id);
            displayAllData();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Invalid ID format.");
        }
    }
    }//GEN-LAST:event_btndelActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
          if(sellerid.getText().equals("")||sellername.getText().equals("")||sellerage.getText().equals("")||sellergender.getText().equals("")||selleraddress.getText().equals("")||sellercontact.getText().equals(""))
        {
           JOptionPane.showMessageDialog(null, "All fileds must be filled");
        }
        else if(checkID())
        {
             JOptionPane.showMessageDialog(null, "ID or contact number alteady exist");
        }
        else
        {
           try{
           Seller seller=new Seller();  
           seller.setId(Integer.parseInt(sellerid.getText()));
           seller.setAge(Integer.parseInt(sellerage.getText()));
           seller.setSupname(sellername.getText());
           seller.setGender(sellergender.getText());
           seller.setAddress(selleraddress.getText());
           seller.setContactnum(sellercontact.getText());
           
           allsellers.add(seller);
           
           sellerid.setText("");
            sellerage.setText("");
             sellername.setText("");
              sellergender.setText("");
               selleraddress.setText("");
                sellercontact.setText("");
                 
                 displayAllData();
                 saveAllData();
           
           }
           
           catch(Exception e)
           {
               JOptionPane.showMessageDialog(null, "ID and age must be Integer"); 
           }
        }
    }                                    

 void saveAllData() {
    try {
        FileWriter filewriter = new FileWriter("supplierdata.txt"); 
        for(Seller seller : allsellers) {
            filewriter.write(seller.getId() + ";" + seller.getAge() + ";" + seller.getSupname() + ";" + seller.getGender() + ";" + seller.getAddress() + ";" + seller.getContactnum()+"\n");
             filewriter.write(seller + "\n");
        }
        
        filewriter.close();
    } catch(Exception e) {
        e.printStackTrace();
    }
}
   
public void deleteSeller(int id) {
    Iterator<Seller> iterator = allsellers.iterator();
    while (iterator.hasNext()) {
        Seller seller = iterator.next();
        if (seller.getId() == id) {
            iterator.remove();
            saveAllData(); // update the data file
            return; // exit the method after deleting the first matching supplier
        }
    }
    // if no supplier with the given ID was found
    JOptionPane.showMessageDialog(null, "No supplier with ID " + id + " found.");
} 
    
    
   boolean checkID() {
    Queue<Seller> sellersQueue = new LinkedList<>(allsellers);
    Seller seller;

    while ((seller = sellersQueue.poll()) != null) {
        if (sellerid.getText().equals(String.valueOf(seller.getId())) || 
            sellercontact.getText().equals(seller.getContactnum())) {
            return true;
        }
    }
    return false;
   
    }//GEN-LAST:event_btnsaveActionPerformed

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
        if(sellerid.getText() == null || sellerid.getText().equals("")) {
            return;
        }
        
        Seller foundSeller = searchseller(sellerid.getText());
        if(foundSeller != null) {
            sellerid.setText(foundSeller.getId() + "");
            sellername.setText(foundSeller.getSupname());
            sellerage.setText(foundSeller.getAge() + "");
            sellergender.setText(foundSeller.getGender());
            selleraddress.setText(foundSeller.getAddress());
            sellercontact.setText(foundSeller.getContactnum());
            
        } else {
            JOptionPane.showMessageDialog(null, "Seller not found.");
        }
    }
    
private Seller searchseller(String input) {
        Queue<Seller> queue = new LinkedList<>(allsellers);
        while(!queue.isEmpty()) {
            Seller seller = queue.remove();
            if(seller.getId() == Integer.parseInt(input) || seller.getContactnum().equals(input)) {
                return seller;
            }
        }
        return null;
    
    }//GEN-LAST:event_btnsearchActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        mainpage m1 = new mainpage();
        m1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sellers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sellers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sellers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sellers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sellers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndel;
    private javax.swing.JButton btnsave;
    private javax.swing.JButton btnsearch;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField selleraddress;
    private javax.swing.JTextField sellerage;
    private javax.swing.JTextField sellercontact;
    private javax.swing.JTextField sellergender;
    private javax.swing.JTextField sellerid;
    private javax.swing.JTextField sellername;
    private javax.swing.JTextArea sellertxt;
    // End of variables declaration//GEN-END:variables
}
